-- ************************************************************
-- *** Creación del Tablespace del esquema de Configuración ***
-- ************************************************************

-- ****************** TABLESPACE PARA EL MODULO DE CONFIGURACIÓN *****************
CREATE TABLESPACE "MONITORIZA_CONFIGURACION_TABLESPACE" 
	DATAFILE 'RUTA_ALMACENAMIENTO_ESQUEMA/CONFIGURACION_TABLESPACE_000001.ora' SIZE 128M AUTOEXTEND ON;

-- ****************************** USUARIO PROPIETARIO **********************************
CREATE USER "MONITORIZA_CONFIGOWNER"  PROFILE "DEFAULT"
	IDENTIFIED BY "XXXXX" DEFAULT TABLESPACE "MONITORIZA_CONFIGURACION_TABLESPACE"
		ACCOUNT UNLOCK;

GRANT ALTER ANY TABLE TO "MONITORIZA_CONFIGOWNER";
GRANT CREATE ANY TABLE TO "MONITORIZA_CONFIGOWNER";
GRANT DROP ANY TABLE TO "MONITORIZA_CONFIGOWNER";
GRANT "RESOURCE" TO "MONITORIZA_CONFIGOWNER";
GRANT "CONNECT" TO "MONITORIZA_CONFIGOWNER";

COMMIT;
