-- **********************************************************************
-- ************* Creación del Usuario de Configuración ******************
-- **********************************************************************

CREATE USER "CONFIGURACION"  PROFILE "DEFAULT" 
    IDENTIFIED BY "PASSWORD" DEFAULT TABLESPACE "MONIT_CONFIGURACION_TABLESPACE" 
        ACCOUNT UNLOCK;

GRANT INSERT ON "MONIT_CONFIGOWNER"."USER_MONITORIZA" TO "CONFIGURACION";
GRANT SELECT ON "MONIT_CONFIGOWNER"."USER_MONITORIZA" TO "CONFIGURACION";
GRANT UPDATE ON "MONIT_CONFIGOWNER"."USER_MONITORIZA" TO "CONFIGURACION";
GRANT DELETE ON "MONIT_CONFIGOWNER"."USER_MONITORIZA" TO "CONFIGURACION";

GRANT SELECT,ALTER ON "MONIT_CONFIGOWNER"."SQ_USER_MONITORIZA" TO "CONFIGURACION";

GRANT INSERT ON "MONIT_CONFIGOWNER"."ALARM_MONITORIZA" TO "CONFIGURACION";
GRANT SELECT ON "MONIT_CONFIGOWNER"."ALARM_MONITORIZA" TO "CONFIGURACION";
GRANT UPDATE ON "MONIT_CONFIGOWNER"."ALARM_MONITORIZA" TO "CONFIGURACION";
GRANT DELETE ON "MONIT_CONFIGOWNER"."ALARM_MONITORIZA" TO "CONFIGURACION";

GRANT SELECT,ALTER ON "MONIT_CONFIGOWNER"."SQ_ALARM_MONITORIZA" TO "CONFIGURACION";

GRANT INSERT ON "MONIT_CONFIGOWNER"."MAIL_MONITORIZA" TO "CONFIGURACION";
GRANT SELECT ON "MONIT_CONFIGOWNER"."MAIL_MONITORIZA" TO "CONFIGURACION";
GRANT UPDATE ON "MONIT_CONFIGOWNER"."MAIL_MONITORIZA" TO "CONFIGURACION";
GRANT DELETE ON "MONIT_CONFIGOWNER"."MAIL_MONITORIZA" TO "CONFIGURACION";

GRANT SELECT,ALTER ON "MONIT_CONFIGOWNER"."SQ_MAIL_MONITORIZA" TO "CONFIGURACION";

GRANT INSERT ON "MONIT_CONFIGOWNER"."PLATFORM_AFIRMA" TO "CONFIGURACION";
GRANT SELECT ON "MONIT_CONFIGOWNER"."PLATFORM_AFIRMA" TO "CONFIGURACION";
GRANT UPDATE ON "MONIT_CONFIGOWNER"."PLATFORM_AFIRMA" TO "CONFIGURACION";
GRANT DELETE ON "MONIT_CONFIGOWNER"."PLATFORM_AFIRMA" TO "CONFIGURACION";

GRANT SELECT,ALTER ON "MONIT_CONFIGOWNER"."SQ_PLATFORM_AFIRMA" TO "CONFIGURACION";

GRANT INSERT ON "MONIT_CONFIGOWNER"."PLATFORM_TSA" TO "CONFIGURACION";
GRANT SELECT ON "MONIT_CONFIGOWNER"."PLATFORM_TSA" TO "CONFIGURACION";
GRANT UPDATE ON "MONIT_CONFIGOWNER"."PLATFORM_TSA" TO "CONFIGURACION";
GRANT DELETE ON "MONIT_CONFIGOWNER"."PLATFORM_TSA" TO "CONFIGURACION";

GRANT SELECT,ALTER ON "MONIT_CONFIGOWNER"."SQ_PLATFORM_TSA" TO "CONFIGURACION";

GRANT INSERT ON "MONIT_CONFIGOWNER"."SERVICE_MONITORIZA" TO "CONFIGURACION";
GRANT SELECT ON "MONIT_CONFIGOWNER"."SERVICE_MONITORIZA" TO "CONFIGURACION";
GRANT UPDATE ON "MONIT_CONFIGOWNER"."SERVICE_MONITORIZA" TO "CONFIGURACION";
GRANT DELETE ON "MONIT_CONFIGOWNER"."SERVICE_MONITORIZA" TO "CONFIGURACION";

GRANT SELECT,ALTER ON "MONIT_CONFIGOWNER"."SQ_SERVICE_MONITORIZA" TO "CONFIGURACION";

GRANT INSERT ON "MONIT_CONFIGOWNER"."TIMER_MONITORIZA" TO "CONFIGURACION";
GRANT SELECT ON "MONIT_CONFIGOWNER"."TIMER_MONITORIZA" TO "CONFIGURACION";
GRANT UPDATE ON "MONIT_CONFIGOWNER"."TIMER_MONITORIZA" TO "CONFIGURACION";
GRANT DELETE ON "MONIT_CONFIGOWNER"."TIMER_MONITORIZA" TO "CONFIGURACION";

GRANT SELECT,ALTER ON "MONIT_CONFIGOWNER"."SQ_TIMER_MONITORIZA" TO "CONFIGURACION";

GRANT CREATE SYNONYM TO "CONFIGURACION";
GRANT "CONNECT" TO "CONFIGURACION";

COMMIT;
