-- **********************************************************************
-- ************* Creación del Usuario de Configuración ******************
-- **********************************************************************

CREATE USER "CONFIGURACION"  PROFILE "DEFAULT" 
    IDENTIFIED BY "PASSWORD" DEFAULT TABLESPACE "CONFIGURACION_TABLESPACE" 
        ACCOUNT UNLOCK;

GRANT INSERT ON "CONFIGOWNER"."USER_MONITORIZA" TO "CONFIGURACION";
GRANT SELECT ON "CONFIGOWNER"."USER_MONITORIZA" TO "CONFIGURACION";
GRANT UPDATE ON "CONFIGOWNER"."USER_MONITORIZA" TO "CONFIGURACION";
GRANT DELETE ON "CONFIGOWNER"."USER_MONITORIZA" TO "CONFIGURACION";

GRANT SELECT,ALTER ON "CONFIGOWNER"."SQ_USER_MONITORIZA" TO "CONFIGURACION";

GRANT CREATE SYNONYM TO "CONFIGURACION";
GRANT "CONNECT" TO "CONFIGURACION";

COMMIT;
