-- ********************************************************
-- ************** Creación de sinónimos *******************
-- ********************************************************

CREATE SYNONYM "USER_MONITORIZA" FOR "MONIT_CONFIGOWNER"."USER_MONITORIZA";
CREATE SYNONYM "TIMER_MONITORIZA" FOR "MONIT_CONFIGOWNER"."TIMER_MONITORIZA";
CREATE SYNONYM "ALARM_MONITORIZA" FOR "MONIT_CONFIGOWNER"."ALARM_MONITORIZA";
CREATE SYNONYM "MAIL_MONITORIZA" FOR "MONIT_CONFIGOWNER"."MAIL_MONITORIZA";
CREATE SYNONYM "SERVICE_MONITORIZA" FOR "MONIT_CONFIGOWNER"."SERVICE_MONITORIZA";
CREATE SYNONYM "C_PLATFORM_TYPE" FOR "MONIT_CONFIGOWNER"."C_PLATFORM_TYPE";
CREATE SYNONYM "PLATFORM_MONITORIZA" FOR "MONIT_CONFIGOWNER"."PLATFORM_MONITORIZA";
CREATE SYNONYM "R_ALARM_MAIL" FOR "MONIT_CONFIGOWNER"."R_ALARM_MAIL";
CREATE SYNONYM "KEYSTORE" FOR "CONFIGOWNER"."KEYSTORE";
CREATE SYNONYM "SYSTEM_CERTIFICATE" FOR "CONFIGOWNER"."SYSTEM_CERTIFICATE";
CREATE SYNONYM "R_ALARM_MAIL_DEGRADED" FOR "MONIT_CONFIGOWNER"."R_ALARM_MAIL_DEGRADED";
CREATE SYNONYM "R_ALARM_MAIL_DOWN" FOR "MONIT_CONFIGOWNER"."R_ALARM_MAIL_DOWN";

CREATE OR REPLACE SYNONYM "SQ_USER_MONITORIZA" FOR "MONIT_CONFIGOWNER"."SQ_USER_MONITORIZA";
CREATE OR REPLACE SYNONYM "SQ_ALARM_MONITORIZA" FOR "MONIT_CONFIGOWNER"."SQ_ALARM_MONITORIZA";
CREATE OR REPLACE SYNONYM "SQ_MAIL_MONITORIZA" FOR "MONIT_CONFIGOWNER"."SQ_MAIL_MONITORIZA";
CREATE OR REPLACE SYNONYM "SQ_PLATFORM_MONITORIZA" FOR "MONIT_CONFIGOWNER"."SQ_PLATFORM_MONITORIZA";
CREATE OR REPLACE SYNONYM "SQ_SERVICE_MONITORIZA" FOR "MONIT_CONFIGOWNER"."SQ_SERVICE_MONITORIZA";
CREATE OR REPLACE SYNONYM "SQ_TIMER_MONITORIZA" FOR "MONIT_CONFIGOWNER"."SQ_TIMER_MONITORIZA";
CREATE OR REPLACE SYNONYM "SQ_SYSTEM_CERTIFICATE" FOR "CONFIGOWNER"."SQ_SYSTEM_CERTIFICATE";
CREATE OR REPLACE SYNONYM "SQ_R_ALARM_MAIL_DEGRADED" FOR "CONFIGOWNER"."SQ_R_ALARM_MAIL_DEGRADED";
CREATE OR REPLACE SYNONYM "SQ_R_ALARM_MAIL_DOWN" FOR "CONFIGOWNER"."SQ_R_ALARM_MAIL_DOWN";

COMMIT;
