-- ************************************************************
-- *** Creación del Tablespace del esquema de Configuración ***
-- ************************************************************

-- ****************** TABLESPACE PARA EL MODULO DE CONFIGURACIÓN *****************
DROP TABLESPACE MONIT_CONFIGURACION_TABLESPACE INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

CREATE TABLESPACE "MONIT_CONFIGURACION_TABLESPACE" 
	DATAFILE 'C:/oraclexe/datasources/monitoriza/1.1/CONFIGURACION_TABLESPACE_000001.ora' SIZE 16M AUTOEXTEND ON;

-- ****************************** USUARIO PROPIETARIO **********************************

DROP USER MONIT_CONFIGOWNER CASCADE; 

CREATE USER "MONIT_CONFIGOWNER"  PROFILE "DEFAULT"
	IDENTIFIED BY "12345" DEFAULT TABLESPACE "MONIT_CONFIGURACION_TABLESPACE"
		ACCOUNT UNLOCK;

GRANT ALTER ANY TABLE TO "MONIT_CONFIGOWNER";
GRANT CREATE ANY TABLE TO "MONIT_CONFIGOWNER";
GRANT DROP ANY TABLE TO "MONIT_CONFIGOWNER";
GRANT "RESOURCE" TO "MONIT_CONFIGOWNER";
GRANT "CONNECT" TO "MONIT_CONFIGOWNER";

COMMIT;