//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.16 at 12:35:55 PM CET 
//


package es.gob.monitoriza.invoker.http.conf.messages;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AttributeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AttributeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="familyName"/&gt;
 *     &lt;enumeration value="firstName"/&gt;
 *     &lt;enumeration value="dateOfBirth"/&gt;
 *     &lt;enumeration value="personIdentifier"/&gt;
 *     &lt;enumeration value="legalName"/&gt;
 *     &lt;enumeration value="legalPersonIdentifier"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AttributeType")
@XmlEnum
public enum AttributeType {

    @XmlEnumValue("familyName")
    FAMILY_NAME("familyName"),
    @XmlEnumValue("firstName")
    FIRST_NAME("firstName"),
    @XmlEnumValue("dateOfBirth")
    DATE_OF_BIRTH("dateOfBirth"),
    @XmlEnumValue("personIdentifier")
    PERSON_IDENTIFIER("personIdentifier"),
    @XmlEnumValue("legalName")
    LEGAL_NAME("legalName"),
    @XmlEnumValue("legalPersonIdentifier")
    LEGAL_PERSON_IDENTIFIER("legalPersonIdentifier");
    private final String value;

    AttributeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AttributeType fromValue(String v) {
        for (AttributeType c: AttributeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
