//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.16 at 11:49:09 AM CET 
//


package es.gob.monitoriza.invoker.http.conf.messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Configuración de la conexión de la petición. Opcional.
 * 			
 * 
 * <p>Java class for ConnectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConnectionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="proxy" type="{urn:es:gob:monitoriza:invoker:http:conf:messages:1.0.0}ProxyConfType" minOccurs="0"/&gt;
 *         &lt;element name="authenticationMutual" type="{urn:es:gob:monitoriza:invoker:http:conf:messages:1.0.0}AuthenticationMutualType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConnectionType", propOrder = {
    "proxy",
    "authenticationMutual"
})
public class ConnectionType {

    protected ProxyConfType proxy;
    protected AuthenticationMutualType authenticationMutual;

    /**
     * Gets the value of the proxy property.
     * 
     * @return
     *     possible object is
     *     {@link ProxyConfType }
     *     
     */
    public ProxyConfType getProxy() {
        return proxy;
    }

    /**
     * Sets the value of the proxy property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxyConfType }
     *     
     */
    public void setProxy(ProxyConfType value) {
        this.proxy = value;
    }

    /**
     * Gets the value of the authenticationMutual property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationMutualType }
     *     
     */
    public AuthenticationMutualType getAuthenticationMutual() {
        return authenticationMutual;
    }

    /**
     * Sets the value of the authenticationMutual property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationMutualType }
     *     
     */
    public void setAuthenticationMutual(AuthenticationMutualType value) {
        this.authenticationMutual = value;
    }

}
