//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.16 at 12:35:55 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:es:gob:monitoriza:invoker:http:conf:messages:1.0.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package es.gob.monitoriza.invoker.http.conf.messages;
