//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.16 at 11:49:09 AM CET 
//


package es.gob.monitoriza.invoker.http.conf.messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Configuración de la conexión de la petición. Opcional.
 * 			
 * 
 * <p>Java class for RequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="httpRequest" type="{urn:es:gob:monitoriza:invoker:http:conf:messages:1.0.0}HttpRequestType" minOccurs="0"/&gt;
 *         &lt;element name="samlRequest" type="{urn:es:gob:monitoriza:invoker:http:conf:messages:1.0.0}SamlRequestType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestType", propOrder = {
    "httpRequest",
    "samlRequest"
})
public class RequestType {

    protected HttpRequestType httpRequest;
    @XmlElement(required = true)
    protected SamlRequestType samlRequest;

    /**
     * Gets the value of the httpRequest property.
     * 
     * @return
     *     possible object is
     *     {@link HttpRequestType }
     *     
     */
    public HttpRequestType getHttpRequest() {
        return httpRequest;
    }

    /**
     * Sets the value of the httpRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link HttpRequestType }
     *     
     */
    public void setHttpRequest(HttpRequestType value) {
        this.httpRequest = value;
    }

    /**
     * Gets the value of the samlRequest property.
     * 
     * @return
     *     possible object is
     *     {@link SamlRequestType }
     *     
     */
    public SamlRequestType getSamlRequest() {
        return samlRequest;
    }

    /**
     * Sets the value of the samlRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamlRequestType }
     *     
     */
    public void setSamlRequest(SamlRequestType value) {
        this.samlRequest = value;
    }

}
