//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.16 at 11:49:09 AM CET 
//


package es.gob.monitoriza.invoker.http.conf.messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Configuración de la petición Saml
 * 			
 * 
 * <p>Java class for SamlRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SamlRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="assertionConsumerServiceURL" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SPApplication" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="providerName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SPType" type="{urn:es:gob:monitoriza:invoker:http:conf:messages:1.0.0}SPRequestType" minOccurs="0"/&gt;
 *         &lt;element name="attributes" type="{urn:es:gob:monitoriza:invoker:http:conf:messages:1.0.0}AttributesType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SamlRequestType", propOrder = {
    "assertionConsumerServiceURL",
    "spApplication",
    "providerName",
    "spType",
    "attributes"
})
public class SamlRequestType {

    @XmlElement(required = true)
    protected String assertionConsumerServiceURL;
    @XmlElement(name = "SPApplication", required = true)
    protected String spApplication;
    @XmlElement(required = true)
    protected String providerName;
    @XmlElement(name = "SPType")
    @XmlSchemaType(name = "string")
    protected SPRequestType spType;
    protected AttributesType attributes;

    /**
     * Gets the value of the assertionConsumerServiceURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssertionConsumerServiceURL() {
        return assertionConsumerServiceURL;
    }

    /**
     * Sets the value of the assertionConsumerServiceURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssertionConsumerServiceURL(String value) {
        this.assertionConsumerServiceURL = value;
    }

    /**
     * Gets the value of the spApplication property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPApplication() {
        return spApplication;
    }

    /**
     * Sets the value of the spApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPApplication(String value) {
        this.spApplication = value;
    }

    /**
     * Gets the value of the providerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderName() {
        return providerName;
    }

    /**
     * Sets the value of the providerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderName(String value) {
        this.providerName = value;
    }

    /**
     * Gets the value of the spType property.
     * 
     * @return
     *     possible object is
     *     {@link SPRequestType }
     *     
     */
    public SPRequestType getSPType() {
        return spType;
    }

    /**
     * Sets the value of the spType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SPRequestType }
     *     
     */
    public void setSPType(SPRequestType value) {
        this.spType = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * @return
     *     possible object is
     *     {@link AttributesType }
     *     
     */
    public AttributesType getAttributes() {
        return attributes;
    }

    /**
     * Sets the value of the attributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributesType }
     *     
     */
    public void setAttributes(AttributesType value) {
        this.attributes = value;
    }

}
